const WHITE = '#FFFFFF';
const LOTION = '#FDFDFD';
const CULTURED = '#F5F5F6';
const BRIGHT_GRAY = '#E9EBEF';
const ANTI_FLASH_WHITE = '#F0F4F8';
const LIGHT_SILVER = '#D5D6D9';
const LIGHT_BLUE = '#EBF0FB';
const GRAY = '#B9B9B9';
const CADET_GRAY = '#919CB3';
const GUNMETAL = '#2C3342';
const CHINESE_BLACK = '#171717';
const SONIC_SILVER = '#6C6E7F';
const ALICE_BLUE = '#F1F8FF';
const AZUREISH_WHITE = '#D6E7F7';
const BRIGHT_NAVY_BLUE = '#196FD2';
const GREEN_BLUE = '#165EB1';
const PALE_CERULEAN = '#99C2EC';
const FRENCH_SKY_BLUE = '#79B1FF';
const FLASH_WHITE = '#F5EEFA';
const DARK_ORCHID = '#9547D1';
const SEASHELL = '#FFF7EC';
const YELLOW_ORANGE = '#F3A739';
const LOVENDER_BLUSH = '#FEEFEF';
const DARK_CORAL = '#CE5347';
const METALLIC_RED = '#A13126';
const VERSE_GREEN = '#20820D';
const NYANZA = '#E8FBE5';
const LIME_GREEN = '#3EDE3A';
const TOPAZ = '#FFC97C';
const BLUEBERRY = '#4D94FF';
const VAMPIRE_BLACK = '#060606';
const RAISIN_BLACK = '#252525';
const JET = '#313139';
const CHARADE = '#2A2F38';
const STORM_GRAY = '#71737A';
const METALLIC_SILVER = '#A1A4AF';
const PLATINUM = '#E3E2E6';
const ROMAN_SILVER = '#8D9099';
const BLUE_JEANS = '#5BB0FF';
const LIGHT_SKY_BLUE = '#97CDFF';
const GLAUCOUS = '#6B85AD';
const ENGLISH_VIOLET = '#e8fbe5';
const PINK_LACE = '#F9D8FD';
const PHILIPPINE_GOLD = '#AF7400';
const MELON = '#FFB4A9';
const PALE_PING = '#FFDAD4';
const IGUANA_GREEN = '#7EB573';
const MUGHAL_GREEN = '#2E5E24';
const BLACK_CORAL = '#555A67';
const LIGHT_GHOST = '#00000014';
const MOON_LIGHT = '#FFFFFFСС';

export {
  ALICE_BLUE,
  ANTI_FLASH_WHITE,
  AZUREISH_WHITE,
  BLACK_CORAL,
  BLUE_JEANS,
  BLUEBERRY,
  BRIGHT_GRAY,
  BRIGHT_NAVY_BLUE,
  CADET_GRAY,
  CHARADE,
  CHINESE_BLACK,
  CULTURED,
  DARK_CORAL,
  DARK_ORCHID,
  ENGLISH_VIOLET,
  FLASH_WHITE,
  FRENCH_SKY_BLUE,
  GLAUCOUS,
  GRAY,
  GREEN_BLUE,
  GUNMETAL,
  IGUANA_GREEN,
  JET,
  LIGHT_GHOST,
  LIGHT_SILVER,
  LIGHT_BLUE,
  LIGHT_SKY_BLUE,
  LIME_GREEN,
  LOTION,
  LOVENDER_BLUSH,
  MELON,
  METALLIC_RED,
  METALLIC_SILVER,
  MOON_LIGHT,
  MUGHAL_GREEN,
  NYANZA,
  PALE_CERULEAN,
  PALE_PING,
  PHILIPPINE_GOLD,
  PINK_LACE,
  PLATINUM,
  RAISIN_BLACK,
  ROMAN_SILVER,
  SEASHELL,
  SONIC_SILVER,
  STORM_GRAY,
  TOPAZ,
  VAMPIRE_BLACK,
  VERSE_GREEN,
  WHITE,
  YELLOW_ORANGE,
};
